[details]
from = " gAAAAABm-a-TQGYoTz53aenY3VFxf0fXW7ioj1_yvb5Rs90DulUc0kvFPGDmokbPN8OctiO47Pb6pIMhrA9fo65oH9q30zoihO4ZoHzNuTXdOvs9L8hNrSE5MLPBPQzrLsD5RPFE4-gNfB-WS9A8rQq7K6pkv4p6iFOgtHDA4a43GofL-ySgoxAB1nFMMHCSkNMd05kTwPTInnQKZVVwDQI7xRfOKcsD7RJjV5MJ857YHjh-zbw70uDjrGVx0zjPkj-iibN8tsTqGitP3-3b8oFQLY8a-d4KTalRpafwgl2Qu8pPJ8tPn6ZEJu745gZ38j3j2I97FzWWQBY6JekZHzJQ5yOoP9fxRw=="
bill_to = "gAAAAABm-a-wQSXPDKr4UqteMHvfM9V87OT8xIKP3eQh6OqzbafP19htorI7UfVLYfRwkKAdjvLVmUFhYDvzxg6t39pkm6Oalcl7xxNvlweCkVVa1MJu2c65xohXuroAoudCZ162sNmawb3ntuofVsOf7pLACLC9hFAOBGHhgZHMi-_QjdpwfJU="
terms = "gAAAAABm-bATCFFJ_v4vqFqcwAQvJ1X6K75kXRBMNmk-kHs7a1liCeoBnAjQqJvRRlzRzlQGyWslRkS5Af4HqGAbPNizeB2E-RtfvfefozMGFGdxC7g1Pw-rKeDYSvgrLSGNar6PwkLTYzvqG9TA_ZdM4pj2ifSldw7sSAFaLPF--mnZrmOYUTQUMS-Lx3a7_fHPaf_ZNon-aCtaz1XN0tPTx DPGeEKwHp3YVE0C4oD3gEV-KLSGU-Tc9ZmhOGF8PkzP-9N3HqXBMN8Q7s1VIrHvWdA6P63teNuA0aXVZDbHzbeqKmno41y4EPmvxE6a3s8pk8aq8kwYIgMuAdPGQCZLKq6bI4gi09ZxgVIhVOBhXJ4akNhp0yh1pxp-_3Bg6VtngeUkv3VHu2fTUjS16Mr1UsYSQOdHr043qn25SPoeCVKJ9tFTLC3xmqfWEkuhFs98EbYLcfgV"
description = "gAAAAABm-cEzzj7wAAWtVoA5SuYPh94lxnGqDXymjImffHd4p8GTtihIYZte1ZVkX8znghHO7mW7QfT9D34hYdbshhZZtxGEWOlyfhXxavE3lRzxTfJDW2CcjObrvm7dXmodKVlmhitO"
rate = "gAAAAABm-bBV2Ht-Gpp_VSHH0Bk6VUUyyftX4zgJB3Dy33eB32YiqFB2RdIKJQpSBR4mGBwMQl-sdC-4z1bCfouwSzIaeq9wNA=="

[http]
url = "gAAAAABm-bBlI7i8fmylOGqUvJcmgZOxekJfdBddtsqFCKxMuPJK7D8RNTd4iX8RmbFtyjHB6BubDQtqCTM0o1O6tVWK4OrqFXTUpHE35qpQUsz9BZuwqFk="

[reference]
start = "gAAAAABm-bB8vNBrJtSVbdj3ey0UUP2BLaPo9zj25-vK1fVi6Xh1LgqV2amK18DJkdFu-H4mysKxYQjECK3SyzOvPmN2bBk9-Q=="

[auth]
username="gAAAAABm-ceT42IV4thkFvYH6l27QEabZvoTY696UAo_4SoY3NeoqpPgncRyywCtEm5IsKh876rT74GaZrRbJbMTUELuYkMXOQ=="
password="gAAAAABm-cek7SDViGHA6Cg1zugsJp6ii3821zigKptMpvu556xNf_ZMjBcbMmF3PwHTp99iZ0NyIHrUizkx0oLOln1TbJwx1g=="